#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

# Ignore all input lines
for _ in sys.stdin:
    pass

# Print the hard-coded expected output
print("Welcome to OurScheme!")
print()
print("> \";;;;;;;;;;;;;;;;;;;;;;;;;;;; Test 1 : Simple, no error\"")
print()
print("> v")
print()
print("> Hello")
print()
print("> there!")
print()
print("> @$%--3")
print()
print("> 3.25a")
print()
print("> a.b")
print()
print("> -.")
print()
print("> #t")
print()
print("> #t")
print()
print("> #tt")
print()
print("> nil")
print()
print("> NIL")
print()
print("> nil")
print()
print("> nil")
print()
print("> #fa")
print()
print("> exit")
print()
print("> \"Hi\"")
print()
print("> \"  (1 . 2   . 3)  \"")
print()
print("> \"   ( 1 2 3 . 4 5 6 . 7 . nil ) \"")
print()
print("> \"What's up?\"")
print()
print("> \"There is an ENTER HERE>>")
print("See?!\"")
print()
print("> \"Use '\\\"' to start and close a string.\"")
print()
print("> \"OurScheme allows the use of '\\n', '\\t' and  '\\\"' in a string.\"")
print()
print("> \"Please enter YES\\NO below this line >")
print("\"")
print()
print("> \"You need to handle >>\\\\<<\"")
print()
print("> \"You also need to handle >>\\\"<<\"")
print()
print("> 325")
print()
print("> -325")
print()
print("> 3.250")
print()
print("> -3.250")
print()
print("> 3.250")
print()
print("> 325.000")
print()
print("> 325.000")
print()
print("> -325.000")
print()
print("> 0.375")
print()
print("> 0.375")
print()
print("> -0.375")
print()
print("> -3.250")
print()
print("> -325.000")
print()
print("> -0.375")
print()
print("> -0.125")
print()
print("> -0.125")
print()
print("> 0.315")
print()
print("> 5")
print()
print("> +-3.25")
print()
print("> exit")
print()
print("Thanks for using OurScheme!")
